// <auto-generated />
using System;
using HotelBooking.API.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelBooking.API.Migrations
{
    [DbContext(typeof(HotelBookingDBContext))]
    partial class HotelBookingDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelBooking.API.DbModels.Facility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FeatureImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeatureName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Features", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FeatureImage = "",
                            FeatureName = "Breakfast"
                        },
                        new
                        {
                            Id = 2,
                            FeatureImage = "",
                            FeatureName = "Wifi"
                        },
                        new
                        {
                            Id = 3,
                            FeatureImage = "",
                            FeatureName = "Parking"
                        },
                        new
                        {
                            Id = 4,
                            FeatureImage = "",
                            FeatureName = "Spa"
                        });
                });

            modelBuilder.Entity("HotelBooking.API.DbModels.HotelBookingInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CostPerNight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomInfoId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RoomInfoId");

                    b.ToTable("HotelBookingInfo", (string)null);
                });

            modelBuilder.Entity("HotelBooking.API.DbModels.HotelFacility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<int>("HotelInformationId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.HasIndex("HotelInformationId");

                    b.ToTable("HotelFeatures", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(3900),
                            FacilityId = 1,
                            HotelInformationId = 1,
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(3901)
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4010),
                            FacilityId = 2,
                            HotelInformationId = 1,
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4011)
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4012),
                            FacilityId = 3,
                            HotelInformationId = 1,
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4013)
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4014),
                            FacilityId = 4,
                            HotelInformationId = 1,
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4015)
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4016),
                            FacilityId = 1,
                            HotelInformationId = 2,
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4016)
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4017),
                            FacilityId = 2,
                            HotelInformationId = 2,
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4018)
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4019),
                            FacilityId = 3,
                            HotelInformationId = 2,
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4019)
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4020),
                            FacilityId = 4,
                            HotelInformationId = 2,
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4021)
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4022),
                            FacilityId = 1,
                            HotelInformationId = 3,
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4023)
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4023),
                            FacilityId = 2,
                            HotelInformationId = 4,
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4024)
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4025),
                            FacilityId = 3,
                            HotelInformationId = 4,
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4026)
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4027),
                            FacilityId = 4,
                            HotelInformationId = 1,
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4027)
                        });
                });

            modelBuilder.Entity("HotelBooking.API.DbModels.HotelInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CostPerNight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HotelInformation", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "address 1",
                            CostPerNight = 1m,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(3703),
                            Description = "Description 1",
                            HotelName = "Name1",
                            Latitude = 0m,
                            Longitude = 0m,
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(3721)
                        },
                        new
                        {
                            Id = 2,
                            Address = "address 1",
                            CostPerNight = 1m,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(3725),
                            Description = "Description 2",
                            HotelName = "Name2",
                            Latitude = 0m,
                            Longitude = 0m,
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(3726)
                        },
                        new
                        {
                            Id = 3,
                            Address = "address 3",
                            CostPerNight = 1m,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(3728),
                            Description = "Description 3",
                            HotelName = "Name 3",
                            Latitude = 0m,
                            Longitude = 0m,
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(3728)
                        },
                        new
                        {
                            Id = 4,
                            Address = "address 3",
                            CostPerNight = 1m,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(3730),
                            Description = "Description 4",
                            HotelName = "Name 4",
                            Latitude = 0m,
                            Longitude = 0m,
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(3731)
                        });
                });

            modelBuilder.Entity("HotelBooking.API.DbModels.HotelRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HotelInformationId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HotelInformationId");

                    b.ToTable("HotelRatings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4051),
                            HotelInformationId = 1,
                            Rating = 4,
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4052)
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4053),
                            HotelInformationId = 1,
                            Rating = 4,
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4054)
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4055),
                            HotelInformationId = 1,
                            Rating = 3,
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4055)
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4056),
                            HotelInformationId = 1,
                            Rating = 4,
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4057)
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4058),
                            HotelInformationId = 2,
                            Rating = 1,
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4058)
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4059),
                            HotelInformationId = 2,
                            Rating = 2,
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4060)
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4061),
                            HotelInformationId = 2,
                            Rating = 3,
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4062)
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4062),
                            HotelInformationId = 2,
                            Rating = 4,
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4063)
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4064),
                            HotelInformationId = 3,
                            Rating = 1,
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4065)
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4066),
                            HotelInformationId = 4,
                            Rating = 2,
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4066)
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4067),
                            HotelInformationId = 4,
                            Rating = 3,
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4068)
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4069),
                            HotelInformationId = 1,
                            Rating = 4,
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4069)
                        });
                });

            modelBuilder.Entity("HotelBooking.API.DbModels.HotelReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HotelInformationId")
                        .HasColumnType("int");

                    b.Property<string>("Review")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HotelInformationId");

                    b.ToTable("HotelReviews", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4088),
                            HotelInformationId = 1,
                            Review = "Good",
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4089)
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4090),
                            HotelInformationId = 1,
                            Review = "Good",
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4091)
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4092),
                            HotelInformationId = 1,
                            Review = "Good",
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4092)
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4093),
                            HotelInformationId = 1,
                            Review = "Happy to be here!",
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4094)
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4095),
                            HotelInformationId = 2,
                            Review = "Good",
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4095)
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4096),
                            HotelInformationId = 2,
                            Review = "Good",
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4098)
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4098),
                            HotelInformationId = 2,
                            Review = "Nice",
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4099)
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4100),
                            HotelInformationId = 2,
                            Review = "Very good",
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4101)
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4102),
                            HotelInformationId = 3,
                            Review = "Good",
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4102)
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4103),
                            HotelInformationId = 4,
                            Review = "Misc",
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4104)
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4105),
                            HotelInformationId = 4,
                            Review = "Bad",
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4106)
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = "",
                            CreatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4106),
                            HotelInformationId = 1,
                            Review = "Good",
                            UpdatedBy = "",
                            UpdatedDate = new DateTime(2022, 11, 13, 11, 13, 14, 426, DateTimeKind.Local).AddTicks(4107)
                        });
                });

            modelBuilder.Entity("HotelBooking.API.DbModels.RoomInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HotelInformationId")
                        .HasColumnType("int");

                    b.Property<string>("RoomNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HotelInformationId");

                    b.ToTable("RoomInformation", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HotelInformationId = 1,
                            RoomNo = "1"
                        },
                        new
                        {
                            Id = 2,
                            HotelInformationId = 1,
                            RoomNo = "2"
                        },
                        new
                        {
                            Id = 3,
                            HotelInformationId = 1,
                            RoomNo = "3"
                        },
                        new
                        {
                            Id = 4,
                            HotelInformationId = 1,
                            RoomNo = "4"
                        },
                        new
                        {
                            Id = 5,
                            HotelInformationId = 2,
                            RoomNo = "1"
                        },
                        new
                        {
                            Id = 6,
                            HotelInformationId = 2,
                            RoomNo = "2"
                        },
                        new
                        {
                            Id = 7,
                            HotelInformationId = 2,
                            RoomNo = "3"
                        },
                        new
                        {
                            Id = 8,
                            HotelInformationId = 2,
                            RoomNo = "4"
                        },
                        new
                        {
                            Id = 9,
                            HotelInformationId = 3,
                            RoomNo = "1"
                        },
                        new
                        {
                            Id = 10,
                            HotelInformationId = 4,
                            RoomNo = "2"
                        },
                        new
                        {
                            Id = 11,
                            HotelInformationId = 4,
                            RoomNo = "3"
                        },
                        new
                        {
                            Id = 12,
                            HotelInformationId = 4,
                            RoomNo = "4"
                        });
                });

            modelBuilder.Entity("HotelBooking.API.DbModels.HotelBookingInfo", b =>
                {
                    b.HasOne("HotelBooking.API.DbModels.RoomInfo", "RoomInfo")
                        .WithMany("HotelBookingInfos")
                        .HasForeignKey("RoomInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomInfo");
                });

            modelBuilder.Entity("HotelBooking.API.DbModels.HotelFacility", b =>
                {
                    b.HasOne("HotelBooking.API.DbModels.Facility", "Feature")
                        .WithMany("HotelFeatures")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelBooking.API.DbModels.HotelInformation", "HotelInformation")
                        .WithMany("HotelFacilities")
                        .HasForeignKey("HotelInformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("HotelInformation");
                });

            modelBuilder.Entity("HotelBooking.API.DbModels.HotelRating", b =>
                {
                    b.HasOne("HotelBooking.API.DbModels.HotelInformation", "HotelInformation")
                        .WithMany("HotelRatings")
                        .HasForeignKey("HotelInformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HotelInformation");
                });

            modelBuilder.Entity("HotelBooking.API.DbModels.HotelReview", b =>
                {
                    b.HasOne("HotelBooking.API.DbModels.HotelInformation", "HotelInformation")
                        .WithMany("HotelReviews")
                        .HasForeignKey("HotelInformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HotelInformation");
                });

            modelBuilder.Entity("HotelBooking.API.DbModels.RoomInfo", b =>
                {
                    b.HasOne("HotelBooking.API.DbModels.HotelInformation", "HotelInformation")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelInformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HotelInformation");
                });

            modelBuilder.Entity("HotelBooking.API.DbModels.Facility", b =>
                {
                    b.Navigation("HotelFeatures");
                });

            modelBuilder.Entity("HotelBooking.API.DbModels.HotelInformation", b =>
                {
                    b.Navigation("HotelFacilities");

                    b.Navigation("HotelRatings");

                    b.Navigation("HotelReviews");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("HotelBooking.API.DbModels.RoomInfo", b =>
                {
                    b.Navigation("HotelBookingInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
